<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Boonex Sounds';

$aLangContent = array(
	'_bx_sounds' => 'Musiques',
	'_bx_sounds_access_denied' => 'Accès refusé',
	'_bx_sounds_action_download' => 'Télécharger',
	'_bx_sounds_action_fave' => 'Favori',
	'_bx_sounds_action_report' => 'Rapport',
	'_bx_sounds_action_share' => 'Partager',
	'_bx_sounds_actions' => 'Actions',
	'_bx_sounds_add' => 'Ajouter des sons',
	'_bx_sounds_add_info' => '<a href="{0}">Cliquer ici</a> pour en ajouter d\'autres.',
	'_bx_sounds_add_objects' => 'Ajouter des musiques',
	'_bx_sounds_admin' => 'Administration',
	'_bx_sounds_admin_activate' => 'Activer',
	'_bx_sounds_admin_deactivate' => 'Désactiver',
	'_bx_sounds_admin_delete' => 'Supprimer',
	'_bx_sounds_admin_feature' => 'Mettre en vedette',
	'_bx_sounds_admin_main' => 'Principal',
	'_bx_sounds_admin_settings' => 'Paramètres',
	'_bx_sounds_admin_unfeature' => 'Annuler le mise en vedette',
	'_bx_sounds_albums' => 'Albums des sons',
    '_bx_sounds_albums_admin' => 'Administration des albums',
    '_bx_sounds_albums_disapproved' => 'Mes albums désapprouvés',
	'_bx_sounds_albums_add' => 'Ajouter un album',
    '_bx_sounds_albums_my' => 'Mes albums',
    '_bx_sounds_albums_count_info' => 'Vous avez {0} <a href="{1}">albums(s)</a>.',
    '_bx_sounds_albums_add_info' => '<a href="{0}">Cliquer ici</a> pour créer un nouvel album.',
    '_bx_sounds_albums_latest' => 'Albums',
    '_bx_sounds_album_add' => 'Ajouter',
	'_bx_sounds_album_add_objects' => 'Ajouter des musiques',
	'_bx_sounds_album_delete' => 'Supprimer un album',
	'_bx_sounds_album_delete_confirm' => 'Confirmer',
	'_bx_sounds_album_delete_error' => '{0} fichier(s) ont été laissés',
	'_bx_sounds_album_delete_success' => 'L\'album a été supprimé avec succès',
	'_bx_sounds_album_delete_warning' => 'Etes-vous sûr de vouloir supprimer l\'album entier et de tout son contenu?',
    '_bx_sounds_album_disapproved' => 'Refusé',
	'_bx_sounds_album_edit' => 'Editer un album',
	'_bx_sounds_album_info' => 'Info de l\'album',
    '_bx_sounds_album_main' => 'Principal',
	'_bx_sounds_album_main_objects' => 'Principal',
    '_bx_sounds_album_manage' => 'Gérer',
	'_bx_sounds_album_manage_objects' => 'Gérer les musiques',
	'_bx_sounds_album_manage_objects_disapproved' => 'Refusé',
	'_bx_sounds_album_manage_objects_failed' => 'Echec',
	'_bx_sounds_album_manage_objects_not_processed' => 'Non traitées',
    '_bx_sounds_album_objects' => 'musiques de cet album',
	'_bx_sounds_album_organize' => 'Organiser',
	'_bx_sounds_album_organize_reverse' => 'Inverser',
	'_bx_sounds_album_organize_save' => 'Enregister les modifications',
	'_bx_sounds_album_save_success' => 'L\'info de l\'album a été sauvé avec succès',
	'_bx_sounds_album_view' => 'Autoriser la vue de l\'album à',
	'_bx_sounds_alert_commented' => '{0} a commenté votre musique',
	'_bx_sounds_alert_rated' => 'Le fichier a été commenté',
	'_bx_sounds_all' => 'Toutes les musiques',
	'_bx_sounds_any' => 'N\'importe laquelle',
	'_bx_sounds_approved' => 'Approuvé',
	'_bx_sounds_bcaption_all' => 'Tous les tags',
	'_bx_sounds_browse' => 'Parcourir',
	'_bx_sounds_browse_by_album' => 'Parcourir les musiques de l\'album "{0}"',
	'_bx_sounds_browse_by_tag' => 'Parcourir les musiques par tag "{0}"',
	'_bx_sounds_browse_by_category' => 'Parcourir les musiques par catégorie "{0}"',
	'_bx_sounds_browse_by_owner' => 'Parcourir les musiques à partir de {0}',
	'_bx_sounds_browse_file' => 'Choisir la musique',
    '_bx_sounds_categories_all' => 'Toutes les catégories',
    '_bx_sounds_choose_uploader' => 'Choisir le téléchargeur',
	'_bx_sounds_categories_all' => 'Toutes les catégories',
	'_bx_sounds_close' => 'Fermer',
	'_bx_sounds_comments' => 'Commentaires',
	'_bx_sounds_count_info' => 'Vous avez {0} <a href="{1}">musique(s)</a> dans cet album.',
	'_bx_sounds_count_status_info' => 'Vous avez {0} <a href="{1}">{2} musique(s)</a> dans ce dossier.',
	'_bx_sounds_couple_Sound_block' => 'Musiques de couple',
	'_bx_sounds_delete' => 'La musique a été supprimée',
	'_bx_sounds_delete_from_album' => 'Supprimer de l\'album',
	'_bx_sounds_delete_error' => 'Erreur de suppression de fichier',
	'_bx_sounds_disapproved' => 'Refusé',
	'_bx_sounds_distribute' => 'Conditions générales pour la diffusion des musiques',
	'_bx_sounds_fav_add' => 'Le fichier a été ajouté à la liste des favoris',
	'_bx_sounds_fav_failed' => 'Le fichier est déjà dans la liste des favoris',
	'_bx_sounds_favorited' => 'Mes musiques favorites',
	'_bx_sounds_featured' => 'Musiques en vedette',
	'_bx_sounds_file_not_found' => 'Musique non trouvée',
	'_bx_sounds_no_file_for_rate' => 'Pas de fichiers pour l\'évaluation',
	'_bx_sounds_failed' => 'Echec',
	'_bx_sounds_file_was_uploaded' => 'Votre musique a été téléchargée (id:{0}) par {1}',
	'_bx_sounds_forbidden' => 'Accès interdit',
	'_bx_sounds_home' => 'Accueil Musiques',
	'_bx_sounds_i_have_the_right_to_distribute' => 'J\'ai le droit de diffuser ces musiques',
	'_bx_sounds_info' => 'Info du fichier',
	'_bx_sounds_info_main' => 'Main Sound info',
	'_bx_sounds_latest' => 'Dernières musiques de cet utilisateur',
	'_bx_sounds_latest_file' => 'Dernières musiques en vedette',
	'_bx_sounds_main' => 'Principal',
	'_bx_sounds_menu_pending' => 'PEn attente',
	'_bx_sounds_menu_profile' => 'Musiques',
	'_bx_sounds_my' => 'Mes musiques',
	'_bx_sounds_msg_page_not_found' => 'Page non trouvée',
	'_bx_sounds_not_found' => 'Fichier non trouvé',
	'_bx_sounds_organize_objects' => 'Organiser',
	'_bx_sounds_pending' => 'En attente',
	'_bx_sounds_plural' => 'Musiques',
	'_bx_sounds_preview' => 'Aperçu',
	'_bx_sounds_previous_rated' => 'Déjà évalué',
	'_bx_sounds_processing' => 'Processing',
	'_bx_sounds_profile_album_name' => '{0}\'s musiques',
	'_bx_sounds_public' => 'Musiques publiques',
	'_bx_sounds_rate' => 'Evaluer',
	'_bx_sounds_rate_header' => 'Evaluer',
	'_bx_sounds_record' => 'Enregistrer',
    '_bx_sounds_regular' => 'Ordinaire',
	'_bx_sounds_related' => 'Musiques associées',
	'_bx_sounds_save_success' => 'L\'info du fichier a été sauvée',
    '_bx_sounds_sbs_main' => 'Mises à jour des musiques',
    '_bx_sounds_sbs_comments' => 'Nouveaux commentaires de la musique',
    '_bx_sounds_sbs_rates' => 'Nouveaux votes de la musique',
	'_bx_sounds_single' => 'Musique',
	'_bx_sounds_size' => 'Taille',
	'_bx_sounds_size_unit' => 'Kb',
	'_bx_sounds_Sound_block' => 'Musiques du profil', 
	'_bx_sounds_special' => 'Musiques en vedette',
    '_bx_sounds_spy_added' => '<a href="{profile_link}">{profile_nick}</a> a ajouté une nouvelle musique <a href="{entry_url}">{entry_caption}</a>',
    '_bx_sounds_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">sound</a> a été commenté par <a href="{profile_link}">{profile_nick}</a>',
    '_bx_sounds_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">musique</a> a été évaluée par <a href="{profile_link}">{profile_nick}</a>',
	'_bx_sounds_submit' => 'Envoyer',
	'_bx_sounds_top' => 'Musiques les mieux notées',
	'_bx_sounds_top_menu_all' => 'Toutes les musiques',
    '_bx_sounds_top_menu_album' => 'Album de musiques',
    '_bx_sounds_top_menu_albums' => 'Albums de musiques',
	'_bx_sounds_top_menu_calendar' => 'Calendrier',
	'_bx_sounds_top_menu_categories' => 'Catégories',
    '_bx_sounds_top_menu_category' => 'Catégorie',
	'_bx_sounds_top_menu_favorited' => 'Mes musiques favorites',
	'_bx_sounds_top_menu_featured' => 'Musiques en vedette',
	'_bx_sounds_top_menu_home' => 'Accueil Musiques',
	'_bx_sounds_top_menu_item' => 'Musiques',
	'_bx_sounds_top_menu_popular' => 'Musiques populaires',
	'_bx_sounds_top_menu_profile' => 'Musiques des profils',
    '_bx_sounds_top_menu_rate' => 'Evaluateur',
	'_bx_sounds_top_menu_search' => 'Recherche',
	'_bx_sounds_top_menu_tags' => 'Tags',
	'_bx_sounds_top_menu_top' => 'Musiques les mieux notées',
	'_bx_sounds_undefined' => 'non défini',
	'_bx_sounds_upl_err' => 'L\'envoi de la musique a échoué (échec pour accepeter l\'information)',
	'_bx_sounds_upl_file_err' => 'L\'envoi de la musique a échoué (erreur musique)',
	'_bx_sounds_upl_succ' => 'La musique a été envoyée avec succès',
	'_bx_sounds_upload' => 'Musiques',
	'_bx_sounds_val_descr_err' => 'La description ne peut pas être vide',
	'_bx_sounds_val_title_err' => 'Le titre ne peut pas être vide',
	'_bx_sounds_view' => 'Lire la musique',
	'_bx_sounds_view_alt_fav'  => 'Favori',
	'_bx_sounds_view_alt_view' => 'Lu',
	'_bx_sounds_wall_added_new' => 'a ajouté une nouvelle',
    '_bx_sounds_wall_music' => 'musique',
    '_bx_sounds_wall_music_private' => 'musique privée',
    '_sbs_txt_title_bx_sounds' => 'abonnement aux musiques',
	'_mma_sounds_add' => 'ajouter des musiques',
	'_mma_sounds_view' => 'lire les musiques', 
	'_mma_sounds_delete' => 'supprimer des musiques',
	'_mma_sounds_download' => 'télécharger des musiques',
	'_mma_sounds_approve' => 'approuver les musiques',
	'_mma_sounds_edit' => 'éditer des musiques',
	'_bx_sounds_profile_sounds' => 'Musiques du profil',
);

?>
