<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$aLangContent = array(
    '_payment_pcaption_details' => 'Détails des paiements',    
    '_payment_pcaption_view_cart' => 'Panier',
    '_payment_pcaption_checkout' => 'Commander',
    '_payment_pcaption_admin' => 'Paiement administration',
    '_payment_pcaption_view_orders' => 'Administration Commande',
    '_payment_pcaption_cart_history' => 'Historique du panier',
	'_payment_pcaption_payment_result' => 'Résultat du paiement',
    '_payment_bcaption_details' => 'Détails des paiements',   
    '_payment_bcaption_settings' => 'Préférences de paiement',
    '_payment_bcaption_cart_featured' => 'Panier du site',
    '_payment_bcaption_cart_common' => 'Membres\' Paniers',
    '_payment_bcaption_checkout' => 'Commander',
    '_payment_bcaption_pending_orders' => 'Commandes en attente',
    '_payment_bcaption_processed_orders' => 'Les commandes traitées',
    '_payment_bcaption_cart_history' => 'Historique du panier',
	'_payment_bcaption_payment_result' => 'Résultat de paiement',
    '_payment_msg_no_results' => 'Vide',
	'_payment_details_return_url' => 'URL de retour de données',
    '_payment_details_submit' => 'Saver',
    '_payment_add_to_cart' => 'Ajouter au panier',
    '_payment_err_wrong_data' => 'Données incorrect',
    '_payment_err_required_login' => 'Vous devez vous identifier',
    '_payment_err_purchase_from_yourself' => 'Vous ne pouvez pas acheter votre propre article',
    '_payment_err_inactive_vendor' => 'Le vendeur n\'a pas le statut actif',
    '_payment_err_not_accept_payments' => 'Le vendeur n\'accepte pas les paiements',
    '_payment_err_incorrect_provider' => 'Fournisseur de paiement incorrecte ou indisponible',
    '_payment_err_unknown_vendor' => 'Fournisseur inconnu',
    '_payment_err_empty_order' => 'La commande est vide',
    '_payment_err_access_db' => 'Erreur d\'accès à la base de données.',    
    '_payment_err_unknown' => 'Une erreur s\'est produite lors de \'opération',
    '_payment_err_empty_orders' => 'Remplissez les numéros de la commande',
    '_payment_err_nothing_selected' => 'Vous devez sélectionner au moins un élément',
    '_payment_err_wrong_client' => 'Nom du client incorrect',
    '_payment_err_self_purchase' => 'Ne peut pas être vendu pour vous',
    '_payment_err_wrong_order' => 'Commande incorrect',
    '_payment_err_wrong_module' => 'Sélectionnez l\'endroit où se trouve l\'élément',
    '_payment_err_empty_items' => 'Il n\'y a pas d\'éléments sélectionnés',
    '_payment_err_wrong_quantity' => 'Quantity spécifié Incorrect',
    '_payment_inf_successfully_added' => 'Cet article a été ajouté à votre panier',
    '_payment_inf_successfully_deleted' => 'Cet article a été supprimé avec succès à partir de votre panier',
    '_payment_inf_successfully_reported' => 'L\'ordre a été signalé avec succès',
    '_payment_txt_items_on' => 'Article(s) sur',
    '_payment_txt_view' => 'voir',
    '_payment_txt_empty' => 'vide',
    '_payment_txt_by' => 'par',
    '_payment_txt_checkout' => 'Commander',
    '_payment_txt_payment_to' => 'Paiement à :',
    '_payment_btn_delete' => 'Supprimer',
    '_payment_btn_checkout' => 'Commander',
    '_payment_btn_process' => 'Processus',
    '_payment_btn_cancel' => 'Commander',
    '_payment_btn_report' => 'Rapport',
    '_payment_btn_add' => 'Ajouter',
    '_payment_btn_manual_order' => 'Manuel de commande',
    '_payment_btn_settings' => 'Paramètres',
    '_payment_btn_orders_processed' => 'Traité',
    '_payment_btn_orders_pending' => 'En attente',
    '_payment_btn_history' => 'Historique',
    '_payment_btn_cart' => 'Cart',
    '_payment_tbar_item_caption' => 'Panier',
    '_payment_tbar_item_description' => 'Panier',
    '_payment_tmenu_payments' => 'Paiements',
    '_payment_tmenu_cart' => 'Cart',
    '_payment_amenu_payment' => 'Paiement',
    '_payment_txt_username_administrator' => 'Administrateur',
    '_payment_txt_shopping_cart' => 'cart',
    '_payment_txt_date' => 'Date',
    '_payment_txt_client' => 'Client',
    '_payment_txt_seller' => 'Vendeur',
    '_payment_txt_order' => 'ID de la Commande',
    '_payment_txt_amount' => 'Montant',
    '_payment_txt_license' => 'Licence',
    '_payment_txt_action' => 'More',
    '_payment_txt_action_more' => 'More',    
    '_payment_txt_processed_with' => 'Traité avec',
    '_payment_txt_message' => 'Résultat',
    '_payment_txt_products' => 'Résultat',
    '_payment_txt_more_products' => 'produits',
    '_payment_txt_more_items' => 'articles',
    '_payment_wcaption_manual_order' => 'Commande manuelle',
    '_payment_wcaption_order_info' => 'Information de la commande',
    '_payment_fldcaption_module' => 'Les articles de',
    '_payment_fldcaption_client' => 'Client',
    '_payment_fldcaption_order' => 'Commande',
    '_payment_ocaption_select' => 'Sélectionnez un',
	'_payment_pp_active_cpt' => 'Actif',
    '_payment_pp_active_dsc' => 'Activer (Désactiver) fournisseur',
    '_payment_pp_mode_cpt' => 'Mode',
    '_payment_pp_mode_dsc' => 'Mode de traiter des paymments',    
    '_payment_pp_mode_live' => 'direct',
    '_payment_pp_mode_test' => 'test',
    '_payment_pp_business_cpt' => 'Affaires',
    '_payment_pp_business_dsc' => 'Adresse électronique d\'affaires',
    '_payment_pp_business_err' => 'Vous devez spécifier une adresse email valide',
    '_payment_pp_prc_type_cpt' => 'type de traitement',
    '_payment_pp_prc_type_dsc' => 'Le type dans lequel les données doivent être traitées. En IPN URL utiliser le mode comme le http://www.your-site.com/your-path/m/payment/act_finalize_checkout/paypal suivantes notifier URL dans votre compta PayPal',
    '_payment_pp_prc_type_direct' => 'direct',
    '_payment_pp_prc_type_pdt' => 'PDT',    
    '_payment_pp_prc_type_ipn' => 'IPN',
    '_payment_pp_cnt_type_cpt' => 'Connection type',
    '_payment_pp_cnt_type_dsc' => 'The type of connection to be used to transfer data',
    '_payment_pp_cnt_type_ssl' => 'SSL',
    '_payment_pp_cnt_type_html' => 'HTML',
    '_payment_pp_token_cpt' => 'Jeton d\'identité',
    '_payment_pp_token_dsc' => 'Jeton d\'identité',
    '_payment_pp_sandbox_cpt' => 'Bac à sablex',    
    '_payment_pp_sandbox_dsc' => 'Adresse e-mail Sandbox',
    '_payment_pp_sandbox_err' => 'Vous devez spécifier une adresse email valide',
    '_payment_pp_err_no_data_given' => 'Aucune donnée fournie.',
	'_payment_pp_err_no_vendor_given' => 'Fournisseur inconnu..',
	'_payment_pp_err_not_completed' => 'Le paiement n\'est pas terminé.',
	'_payment_pp_err_wrong_business' => 'Email du destinataire erroné.',
	'_payment_pp_err_wrong_transaction' => 'Échec lors de la vérification de la transaction.',
	'_payment_pp_err_wrong_verification_status' => 'Aucun statut de vérification reçus.',
	'_payment_pp_err_wrong_amount' => 'Mauvais montant.',
	'_payment_pp_err_wrong_custom_data' => 'Données personnalisées sont incorrect.',
	'_payment_pp_err_already_processed' => 'Le paiement a déjà été traitée.',
	'_payment_pp_msg_verified' => 'Vérifiée avec succès.',
	'_payment_2co_active_cpt' => 'Actif',
	'_payment_2co_active_dsc' => 'Activer (Désactiver) le fournisseur',
	'_payment_2co_mode_cpt' => 'Mode',
	'_payment_2co_mode_dsc' => 'Mode de traiter des paymments',
	'_payment_2co_mode_live' => 'direct',
	'_payment_2co_mode_test' => 'test',
	'_payment_2co_account_id_cpt' => 'Numéro de compte',
	'_payment_2co_account_id_dsc' => 'Votre numéro de compte du fournisseur 2Checkout',
	'_payment_2co_payment_method_cpt' => 'Payment Method',
	'_payment_2co_payment_method_dsc' => 'Cela va régler la sélection par défaut sur l\'étape de la méthode de paiement au cours de la procédure de paiement',
	'_payment_2co_payment_method_cc' => 'Credit Card(CC)',
	'_payment_2co_payment_method_ck' => 'Check(CK)',
	'_payment_2co_payment_method_al' => 'Acculynk PIN-debit(AL)',
	'_payment_2co_payment_method_ppi' => 'PayPal(PPI)',
	'_payment_2co_secret_word_cpt' => 'Mot secret',
	'_payment_2co_secret_word_dsc' => 'Mot secret est utilisé pour calculer la vérification du hachage',
	'_payment_2co_err_no_vendor_given' => 'Fournisseur inconnu',
	'_payment_2co_err_no_data_given' => 'Aucune donnée fournie.',
	'_payment_2co_err_wrong_key' => 'Vérification de la clé est incorrect.',
	'_payment_2co_err_wrong_payment' => 'Mauvais montant du paiement.',
	'_payment_2co_err_already_processed' => 'Le paiement a déjà été traitée',
	'_payment_2co_msg_verified' => 'Vérifiée avec succès.'
);
?>
