<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/
/* COOL-ON-WEB.COM : TRADUCTION FRANÇAISE */
$sLangCategory = 'Boonex Photos';

$aLangContent = array(
  '_bx_photos_caption_browse_by_day' => 'Afficher les photos par jour',
  '_bx_photos' => 'Photos',
  '_bx_photos_access_denied' => 'Accès refusé',
  '_bx_photos_action_view_original' => 'Voir l\'original',
  '_bx_photos_action_fave' => 'Ajouter aux Favoris',
  '_bx_photos_action_unfave' => 'Supprimer les favoris',
  '_bx_photos_action_report' => 'Rapport',
  '_bx_photos_action_share' => 'Partager',
  '_bx_photos_actions' => 'Actions',
  '_bx_photos_add' => 'Ajouter une photo',
  '_bx_photos_add_info' => '<a href="{0}">Cliquez ici </a> pour en ajouter d\'autres',
  '_bx_photos_add_objects' => 'Ajouter des photos',
  '_bx_photos_admin' => 'Administration',
  '_bx_photos_admin_activate' => 'Activer',
  '_bx_photos_admin_deactivate' => 'Désactiver',
  '_bx_photos_admin_delete' => 'Supprimer',
  '_bx_photos_admin_feature' => 'Mettre en vedette',
  '_bx_photos_admin_main' => 'Principal',
  '_bx_photos_admin_settings' => 'Paramètres',
  '_bx_photos_admin_unfeature' => 'Enlever d\'en vedette',
  '_bx_photos_albums_my' => 'Mes albums',
  '_bx_photos_albums_disapproved' => 'Mes albums refusés',
  '_bx_photos_albums_admin' => 'Administration des albums',
  '_bx_photos_albums_add' => 'Ajouter',
  '_bx_photos_albums' => 'Les albums photos',
  '_bx_photos_album_delete_warning' => 'Êtes-vous sûr de vouloir supprimer l\'album entier avec tous ses composants?',
  '_bx_photos_album_delete_success' => 'L\'album a été supprimé avec succès',
  '_bx_photos_album_delete_error' => '{0} fichier(s) restant(s)',
  '_bx_photos_album_delete_confirm' => 'Confirmer',
  '_bx_photos_album_delete' => 'Supprimer',
  '_bx_photos_album_add_objects' => 'Ajouter photos',
  '_bx_photos_album_add' => 'Ajouter',
  '_bx_photos_albums_latest' => 'Albums',
  '_bx_photos_albums_add_info' => '<a href="{0}">Cliquer ici</a> pour créer un nouvel album.',
  '_bx_photos_albums_count_info' => 'Vous avez {0} <a href="{1}">albums(s)</a>.',
  '_bx_photos_album_disapproved' => 'Refusé',
  '_bx_photos_album_edit' => 'Editer l\'album',
  '_bx_photos_album_info' => 'Info de l\'album',
  '_bx_photos_album_main' => 'Principal',
  '_bx_photos_album_objects' => 'Photos de cet album',
  '_bx_photos_album_manage_objects_pending' => 'En attente',
  '_bx_photos_album_manage_objects_disapproved' => 'Refusé',
  '_bx_photos_album_manage_objects' => 'Gérer les photos',
  '_bx_photos_album_manage' => 'Gérer',
  '_bx_photos_album_main_objects' => 'Principal',
  '_bx_photos_album_save_success' => 'L\'info de l\'Album a été sauvé avec succès',
  '_bx_photos_album_organize_reverse' => 'Retourner',
  '_bx_photos_album_organize' => 'Organiser',
	'_bx_photos_album_view' => 'Autoriser le visionnage de l\'album à',
	'_bx_photos_alert_commented' => '{0} a commenté une photo',
	'_bx_photos_alert_rated' => 'Le fichier a été ',
	'_bx_photos_all' => 'Toutes les photos',
	'_bx_photos_any' => 'Tout',
	'_bx_photos_approved' => 'Approuvé',
	'_bx_photos_bcaption_all' => 'Tous les mots clés',
	'_bx_photos_browse' => 'Parcourir',
	'_bx_photos_browse_by_album' => 'Parcourir les photos de l\'album"{0}"',
	'_bx_photos_browse_by_tag' => 'Parcourir les photos par mots clés "{0}"',
	'_bx_photos_browse_by_category' => 'Parcourir les photos par catégorie "{0}"',
	'_bx_photos_browse_by_owner' => 'Parcourir les photos de {0}',
	'_bx_photos_browse_file' => 'Sélectionnez une photo',
    '_bx_photos_categories_all' => 'Toutes les catégories',
	'_bx_photos_choose_uploader' => 'Choisir un fichier',
	'_bx_photos_close' => 'Fermer',
	'_bx_photos_comments' => 'Commentaires',
	'_bx_photos_count_info' => 'Vous avez {0} <a href="{1}">photo(s)</a> dans cet album',
	'_bx_photos_count_status_info' => 'Vous avez {0} <a href="{1}">{2} photo(s)</a> dans cet album.',
	'_bx_photos_couple_photo_block' => 'Photos de couple',
	'_bx_photos_delete' => 'La photo a été supprimée',
	'_bx_photos_delete_from_album' => 'Supprimer l\'album',
	'_bx_photos_delete_error' => 'Suppression du fichier d\erreur',
	'_bx_photos_disapproved' => 'Refusé',
	'_bx_photos_distribute' => 'Termes de conditions pour la diffusion des photos',
	'_bx_photos_embed' => 'Insérer',
	'_bx_photos_Embed' => 'Lien photo Flickr',
	'_bx_photos_Embed_example' => 'Exemple: http://www.flickr.com/photos/39193323@N07/3606466418/',
	'_bx_photos_fav_add' => 'Le fichier a été ajouté à la liste favorite',
    '_bx_photos_fav_failed' => 'Le fichier est déjà dans la liste des favoris',
     '_bx_photos_favorited' => 'Mes photos en favoris',
	'_bx_photos_featured' => 'Photos en vedette',
	'_bx_photos_file_not_found' => 'Photo non trouvée',
	'_bx_photos_file_was_uploaded' => 'Votre photo a été transférée (id:{0}) par {1}',
	'_bx_photos_forbidden' => 'L\'accès est interdit',
	'_bx_photos_home' => 'Accueil photos',
	'_bx_photos_i_have_the_right_to_distribute' => 'Je certifie avoir le droit de diffuser ces photos et que celles-ci n\'enfreignent pas les <a  href="./terms_of_use.php" target="_blank">Conditions d\'utilisation</a>.',
	'_bx_photos_info' => 'Info du fichier',
	'_bx_photos_info_main' => 'Informations sur la photo',
	'_bx_photos_latest' => 'Les dernières photos de cet utilisateur',
	'_bx_photos_latest_file' => 'Dernière photo en vedette',
	'_bx_photos_main' => 'Principal',
	'_bx_photos_menu_pending' => 'En attente',
	'_bx_photos_menu_profile' => 'Photos',
	'_bx_photos_my' => 'Mes photos',
	'_bx_photos_msg_page_not_found' => 'Page introuvable',
	'_bx_photos_no_file_for_rate' => 'Pas de fichiers pour l\'évaluation',
	'_bx_photos_not_found' => 'Fichier non trouvé',
	'_bx_photos_organize_objects' => 'Organiser',
	'_bx_photos_pending' => 'En attendant',
	'_bx_photos_photo_block' => 'Photos de profil', 
	'_bx_photos_plural' => 'photos',
	'_bx_photos_preview' => 'Aperçu',
	'_bx_photos_previous_rated' => 'Les dernières notées',
    '_bx_photos_profile_album_name' => 'Photos de {0}',
  '_bx_photos_public' => 'Les dernières photos !',
  '_bx_photos_rate' => 'Évaluation',
  '_bx_photos_rate_header' => 'Évaluation',
  '_bx_photos_record' => 'Lancer',
  '_bx_photos_regular' => 'Ordinaire',
  '_bx_photos_related' => 'Photos similaires',
  '_bx_photos_save_success' => 'l\'info du fichier a été enregistrée',
    '_bx_photos_sbs_main' => 'Mises à jour de la photo',
    '_bx_photos_sbs_comments' => 'Nouveau commentaire de la photo',
    '_bx_photos_sbs_rates' => 'Nouveau vote de la photo',
	  '_bx_photos_set_as_avatar' => 'Cette photo en avatar',
	'_bx_photos_single' => 'photo',
	'_bx_photos_size' => 'Taille',
	'_bx_photos_size_unit' => 'Kb',
	'_bx_photos_special' => 'Photo en vedette',
	'_bx_photos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> a ajouté une nouvelle photo <a href="{entry_url}">{entry_caption}</a>',
  '_bx_photos_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">photo</a> a été commenté par <a href="{profile_link}">{profile_nick}</a>',
  '_bx_photos_spy_rated' => 'La <a href="{entry_url}">photo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a>  a été évaluée par <a href="{profile_link}">{profile_nick}</a>',
	'_bx_photos_submit' => 'Envoyer',
	'_bx_photos_top' => 'Top photos',
	'_bx_photos_top_menu_albums' => 'Albums photo',
    '_bx_photos_top_menu_album' => 'Album photo',
	'_bx_photos_top_menu_all' => 'Toutes les photos',
	'_bx_photos_top_menu_calendar' => 'Calendrier',
	'_bx_photos_top_menu_categories' => 'Catégories',
	'_bx_photos_top_menu_category' => 'Catégories',
	'_bx_photos_top_menu_favorited' => 'Mes photos préférées',
	'_bx_photos_top_menu_featured' => 'Photo en vedette',
	'_bx_photos_top_menu_home' => 'Accueil des photos',
	'_bx_photos_top_menu_item' => 'Photos',
	'_bx_photos_top_menu_popular' => 'photos populaires',
	'_bx_photos_top_menu_profile' => 'Profils des photos',
	'_bx_photos_top_menu_rate' => 'Évaluer les photos',
	'_bx_photos_top_menu_search' => 'Recherche',
	'_bx_photos_top_menu_tags' => 'Tags',	
	'_bx_photos_top_menu_top' => 'Top photos',
	'_bx_photos_undefined' => 'Indéfini',
	'_bx_photos_upl_err' => 'Échec de l\'envoi des photos (information non accepté)',
	'_bx_photos_upl_file_err' => 'Échec de lors de l\'envoi de photos (erreur photo)',
	'_bx_photos_upl_succ' => 'la photo a été transférée avec succès',
	'_bx_photos_upload' => 'Photos',
	'_bx_photos_val_descr_err' => 'La description ne peut pas être vide',
	'_bx_photos_val_title_err' => 'Titre ne peut pas être vide',
	'_bx_photos_view' => 'Voir la photo ',
	'_bx_photos_view_alt_fav' => 'Favoris',
    '_bx_photos_view_alt_view' => 'Vue',
	'_bx_photos_flickr_key_not_exist' => 'Vous devez ajouter votre clé API Flickr pour utiliser cette fonctionnalité',
    '_bx_photos_emb_err' => 'Échec de l\'insertion de la photo',
    '_bx_photos_wall_added_new' => 'a ajouté une nouvelle',
    '_bx_photos_wall_photo' => 'photo',
    '_bx_photos_wall_photo_private' => 'photo privée',
    '_sbs_txt_title_bx_photos' => 'Souscriptions Photos',
	'_mma_photos_add' => 'ajouter des photos',
	 '_mma_photos_view' => 'voir les photos',
	'_mma_photos_delete' => 'supprimer des photos',
	'_mma_photos_download' => 'télécharger des photos',
	'_mma_photos_approve' => 'approuver des photos',
	'_mma_photos_edit' => 'éditer des photos', 
);

?>
