<?php

/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$aLangContent = array(
    '_bx_ads_added_spy' => '<a href="{profile_link}">{profile_nick}</a> a ajouté une nouvelle annonce <a href="{ads_url}">{ads_caption}</a>',
    '_bx_ads_rated_spy' => '<a href="{profile_link}">{profile_nick}</a> a évélué l\'annonce <a href="{ads_url}">{ads_caption}</a>',
    '_bx_ads_last_featured' => 'Dernière annonce en vedette',
    '_bx_ads_last_ads' => 'Dernières annonces',
    '_bx_ads_Ads' => 'Annonces',
    '_bx_ads_Ad' => 'Annonce',
    '_bx_ads_Buy_Now' => 'Acheter Maintenant',
    '_bx_ads_wholesale' => 'vente en gros',
    '_bx_ads_BuyMsg1' => 'Vous avez choisi l\'option "Acheter Maintenant " pour acheter l\'article ci-dessus. Si vous souhaitez poursuivre et faire un achat immédiat de cet article au prix indiqué ci-dessous, veuillez cliquer sur le bouton «Continuer». Ce sera la clôture des enchères vous permettant de conclure avec le vendeur la transaction.',
    '_bx_ads_BuyDetails1' => 'Détails du montant de l\'achat immédiat:',
    '_bx_ads_BuyMsg2' => 'Votre offre "Acheter Maintenant" a été reçue. Veuillez contacter le vendeur pour conclure la transaction.',
    '_bx_ads_Unit' => 'Unité',
    '_bx_ads_Users_other_listing' => 'Autres annonces de l\'utilisateur',
    '_bx_ads_Manage_ads' => 'Gérer les annonces',
    '_bx_ads_Browse_All_Ads' => 'Parcourir toutes les annonces',
    '_bx_ads_My_Ads' => 'Mes annonces',
    '_bx_ads_Categories' => 'Catégories',
    '_bx_ads_Keywords' => 'Mots-clés',
    '_bx_ads_Posted_by' => 'Publié par',
    '_bx_ads_Details' => 'Détails',
    '_bx_ads_Life_Time' => 'Durée de vie',
    '_bx_ads_Filtered_ads' => 'Annonces filtrées',
    '_bx_ads_Sub_Categories' => 'Sous-catégories',
    '_bx_ads_Add' => 'Publier une annonce',
    '_bx_ads_Description' => 'Description',
    '_bx_ads_CustomField1' => 'Champ personnalisé 1',
    '_bx_ads_CustomField2' => 'Champ personnalisé 2',
    '_bx_ads_Apply' => 'Appliquer',
    '_bx_ads_Activate' => 'Activer',
    '_bx_ads_Back' => 'Retour',
    '_bx_ads_equal' => 'Egal',
    '_bx_ads_bigger' => 'Max',
    '_bx_ads_smaller' => 'Min',
    '_bx_ads_Warn_max_live_days' => 'Votre annonce sera active pendant {0} jours',
    '_bx_ads_Warn_max_file_size' => 'Fichier: {0} trop grand pour télécharger.<br>',
    '_bx_ads_Ad_succ_added' => 'Annonce ajoutée avec succès',
    '_bx_ads_Ad_succ_deleted' => 'Annonce supprimée avec succès',
    '_bx_ads_Ad_fail_delete' => 'Impossible de supprimer l\'annonce',
    '_bx_ads_Moderating' => 'Modération (nouvelles annonces)',
    '_bx_ads_Ad_succ_updated' => 'Annonce mise à jour avec succès',
    '_bx_ads_Filter' => 'Filtre',
    '_bx_ads_Offer_Details' => 'Détails de l\offre',
    '_bx_ads_Main_category_successfully_added' => 'La catégorie principale a été ajoutée avec succès',
    '_bx_ads_Main_category_successfully_deleted' => 'La catégorie principale a été supprimée avec succès',
    '_bx_ads_Main_category_failed_add' => 'Impossible d\'ajouter la catégorie principale',
    '_bx_ads_Sub_category_successfully_added' => 'La sous-catégorie a été ajoutée avec succès',
    '_bx_ads_Sub_category_failed_add' => 'Impossible d\'ajouter une sous-catégorie',
    '_bx_ads_Main_category_failed_delete' => 'Impossible de supprimer la catégorie principale',
    '_bx_ads_Sub_category_successfully_delete' => 'La sous-catégorie supprimée avec succès',
    '_bx_ads_Sub_category_failed_deleted' => 'Impossible de supprimer la sous-catégorie',
    '_bx_ads_All_ads' => 'Toutes les annonces',
    '_bx_ads_Ad_photos' => 'photos de l\'annonce',
    '_bx_ads_user_posted_ad_comment' => '{0} a publié un commentaire à votre annonce',
    '_bx_ads_user_bought_ad' => '{0} souhaite acheter votre annonce',
    '_bx_ads_Custom_Values' => 'Valeurs personnalisées',
    '_bx_ads_Top_Rated' => 'Les mieux notées',
    '_bx_ads_Popular' => 'Populaire',
    '_bx_ads_Calendar' => 'Calendrier',
    '_bx_ads_Featured' => 'En vedette',
    '_bx_ads_Under_Development' => 'En cours de développement',
    '_bx_ads_Ads_Home' => 'Accueil Annonces',
    '_bx_ads_Feature_it' => 'Mettre en vedette',
    '_bx_ads_De-Feature_it' => 'Annuler la mise en vedette',
    '_bx_ads_msg_access_denied' => 'Accès refusé',
    '_bx_ads_pending_approval' => 'En attente d\approbation',
    '_bx_ads_Disapproved' => 'Refusée',
    '_bx_ads_admin_box_desc' => '<div style="text-align: center;margin:10px;">You have {0} <a href="{1}">ads</a>. <a href="{2}">Click here</a> to add one.</div>',
    '_bx_ads_privacy_comment' => 'Autoriser la publication de commentaires à',
    '_bx_ads_privacy_rate' => 'Autoriser l\'évaluation à',
    '_bx_ads_privacy_view' => 'Autoriser de voir à',
    '_bx_ads_Existed_images' => 'Images existantes',
    '_bx_ads_Manage_categories_form' => 'Gérer la forme des catégories',
    '_bx_ads_Administration' => 'Administration',
    '_bx_ads_Add_ad' => 'Ajouter une annonce',
    '_bx_ads_Caption_error' => 'veuillez spécifier la légende de 3 à 255 caractères',
    '_bx_ads_Text_error' => 'veuillez spécifier le texte de publication de 3 à 65535 caractères',
    '_bx_ads_RSS' => 'RSS',
    '_bx_ads_post_text' => 'Publier le texte',
	'_bx_ads_sbs_main' => 'Nouvelles mises à jour dans <b>{0}</b> annonces',
	'_bx_ads_sbs_comments' => 'Nouveaux commentaires pour <b>{0}</b> annonces',
	'_bx_ads_sbs_rates' => 'Nouveaux votes pour <b>{0}</b> annonces',
    '_bx_ads_caption_browse_by_day' => 'Parcourir les publications d\annonces par jour: ',
    '_sbs_txt_title_bx_ads' => 'abonnements aux annonces',
    '_mma_ads_view' => 'voir les annonces',
    '_mma_ads_browse' => 'parcourir les annonces',
    '_mma_ads_search' => 'rechercher les annonces',
    '_mma_ads_add' => 'ajouter des annonces',
    '_mma_ads_edit_any_ad' => 'les annonces éditent n\'importe quelle annonce',
    '_mma_ads_delete_any_ad' => 'les annonces suppriment n\'importe quelle annonce',
    '_mma_ads_approving' => 'approbation des annonces',
    '_bx_ads_caption_city' => 'Ville',
    '_bx_ads_caption_country' => 'Pays',
    '_bx_ads_err_city' => 'veuillez remplir le nom de la ville',
    '_bx_ads_err_country' => 'veuillez spécifier le pays',
    '_bx_ads_add_main_category' => 'Ajouter la catégorie principale',
    '_bx_ads_you_have_purchased_an_item' => 'Vous avez acheté un article',
    '_bx_ads_someone_wants_to_purchase' => 'Quelqu\'un veut acheter un article que vous avez mis en vente',
    '_bx_ads_title_error_desc' => 'Le titre doit comprendre {0} symboles max',
    '_bx_ads_description_error_desc' => 'La description doit comprendre {0} symboles max',
    '_bx_ads_custom_error_desc' => 'Le nom du champ personnalisé{0} doit comprendre {1} symboles max',
    '_bx_ads_choose_custom_action' => 'Choisir l\'action personnalisée',
    '_bx_ads_category_manager' => 'responsable de catégorie',
    '_bx_ads_add_subcategory' => 'Ajouter une sous-catégorie',
    '_bx_ads_parent_category' => 'catégorie parente',
    '_bx_ads_root' => 'Racine',
    '_bx_ads_search_results_by_tag' => 'Résultats de la recherche par tag',
    '_bx_ads_customFieldName1' => 'Champ du nom personalisé 1',
    '_bx_ads_customFieldName2' => 'Champ du nom personnalisé 2',
	'_bx_ads_wall_added_new' => 'a ajouté de vouvelles',
    '_bx_ads_wall_photo' => 'annonce',
    '_bx_ads_category_warn' => 'veuillez choisir la catégorie et la sous-catégorie',
);

?>