<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/
 /*TRADUCTION COOL-ON-WEB.COM !! */
$sLangCategory = 'Boonex Videos';

$aLangContent = array(
 '_bx_videos_caption_browse_by_day' => 'Afficher les vidéos par jour',
 '_bx_videos' => 'Vidéos',
 '_bx_videos_access_denied' => 'Accès interdit',
 '_bx_videos_action_download' => 'Télécharger',
 '_bx_videos_action_fave' => 'Favoris',
 '_bx_videos_action_unfave' => 'Supprimer des favoris',
 '_bx_videos_action_report' => 'Rapporter',
 '_bx_videos_action_share' => 'Partager',
 '_bx_videos_actions' => 'Actions',
 '_bx_videos_add' => 'Ajouter Vidéo',
 '_bx_videos_add_info' => '<a href="{0}">Cliquer ici</a> pour en ajouter d\'autres.',
 '_bx_videos_add_objects' => 'Ajouter Vidéos',
 '_bx_videos_admin' => 'Administration',
 '_bx_videos_admin_activate' => 'Activer',
 '_bx_videos_admin_deactivate' => 'Désactiver', 
 '_bx_videos_admin_delete' => 'Supprimer',
 '_bx_videos_admin_feature' => 'Mettre en avant',
 '_bx_videos_admin_main' => 'Principal',
 '_bx_videos_admin_settings' => 'Réglages',
 '_bx_videos_admin_unfeature' => 'Retirer des appréciés',
 '_bx_videos_albums' => 'Vidéo Albums',
 '_bx_videos_albums_add' => 'Ajouter album',
 '_bx_videos_albums_admin' => 'Albums administration',
 '_bx_videos_albums_disapproved' => 'Mes albums refusés',
 '_bx_videos_albums_my' => 'Mes albums',
 '_bx_videos_albums_count_info' => 'Vous avez {0} <a href="{1}">albums(s)</a>.',
 '_bx_videos_albums_add_info' => '<a href="{0}">Cliquer ici</a> pour créer un nouvel album.',
 '_bx_videos_albums_latest' => 'Albums',
 '_bx_videos_album_add' => 'Ajouter',
 '_bx_videos_album_add_objects' => 'Ajouter Vidéos',
 '_bx_videos_album_delete' => 'Supprimer album',
 '_bx_videos_album_delete_confirm' => 'Confirmer',
 '_bx_videos_album_delete_error' => '{0} fichier(s) ont été laissé',
 '_bx_videos_album_delete_success' => 'Album supprimé',
 '_bx_videos_album_delete_warning' => 'Êtes-vous sûr de vouloir supprimer l\'album et tout son contenu ?',
 '_bx_videos_album_disapproved' => 'Refusé',
 '_bx_videos_album_edit' => 'Editer l\'album',
 '_bx_videos_album_info' => 'Album info',
 '_bx_videos_album_main' => 'Principal',
 '_bx_videos_album_main_objects' => 'Principal',
 '_bx_videos_album_manage' => 'Gérer',
 '_bx_videos_album_manage_objects' => 'Gérer les objets',
 '_bx_videos_album_manage_objects_disapproved' => 'Refusé',
 '_bx_videos_album_manage_objects_failed' => 'Echec',
 '_bx_videos_album_manage_objects_not_processed' => 'Non traité',
 '_bx_videos_album_objects' => 'vidéos de cet album',
 '_bx_videos_album_organize_reverse' => 'Inverser',
 '_bx_videos_album_organize' => 'Organiser',
 '_bx_videos_album_organize_save' => 'Enregistrer les changements',
 '_bx_videos_album_save_success' => 'infos de l\'album enregistrées',
 '_bx_videos_album_view' => 'Autoriser la vue de l\'album à',
 '_bx_videos_alert_commented' => '{0} a commenté votre vidéo',
 '_bx_videos_any' => 'Toutes',
 '_bx_videos_all' => 'Toutes les Vidéos',
 '_bx_videos_alert_rated' => 'Le fichier a été commenté',
 '_bx_videos_approved' => 'Approuvée',
 '_bx_videos_bcaption_all' => 'Toutes les Vidéos',
 '_bx_videos_browse' => 'Parcourir',
 '_bx_videos_browse_by_album' => 'Parcourir les vidéos de l\'album "{0}"',
 '_bx_videos_browse_by_tag' => 'Parcourir les Vidéos par Etiquettes "{0}"',
 '_bx_videos_browse_by_category' => 'Parcourir les Vidéos par catégorie "{0}"',
 '_bx_videos_browse_by_owner' => 'Parcourir les Vidéos de {0}',
 '_bx_videos_browse_file' => 'Choisir la Vidéo',
//'_bx_videos_categories_all' => 'All categories',
 '_bx_videos_choose_uploader' => 'Choisir le téléchargement',
 '_bx_videos_categories_all' => 'Toutes les catégories',
 '_bx_videos_close' => 'Fermer',
 '_bx_videos_comments' => 'Commentaires',
 '_bx_videos_count_info' => 'Vous avez {0} <a href="{1}">Vidéo(s)</a> dans cet album.',
 '_bx_videos_count_status_info' => 'Vous avez {0} <a href="{1}">{2} video(s)</a> dans cet album.',
 '_bx_videos_couple_Video_block' => 'Vidéos du Couple',
 '_bx_videos_delete' => 'Vidéo supprimée',
 '_bx_videos_delete_from_album' => 'Supprimer de l\'album',
 '_bx_videos_delete_error' => 'erreur suppression du fichier',
 '_bx_videos_disapproved' => 'Refusé',
 '_bx_videos_distribute' => 'Termes des conditions de diffusion des Vidéos',
 '_bx_videos_embed' => 'Insérer',
 '_bx_videos_Embed' => 'Lien vidéo Youtube',
 '_bx_videos_Embed_example' => 'Exemple : http://www.youtube.com/watch?v=JFGJRfoK9xQ',
 '_bx_videos_failed' => 'Échoué',
 '_bx_videos_fav_add' => 'Le fichier a été ajouté aux favoris',
 '_bx_videos_fav_remove' => 'Le fichier a été supprimé de la liste des favoris',
 '_bx_videos_featured' => 'Vidéos en vedette',
 '_bx_videos_favorited' => 'Mes Vidéos favorites',
 '_bx_videos_file_not_found' => 'Vidéo non trouvée',
 '_bx_videos_no_file_for_rate' => 'aucun fichier à noter',
 '_bx_videos_file_was_uploaded' => 'Votre vidéo a été ajoutée (id:{0}) par {1}',
 '_bx_videos_forbidden' => 'Accès interdit',
 '_bx_videos_home' => 'Accueil Vidéos',
 '_bx_videos_i_have_the_right_to_distribute' => 'Je certifie avoir le droit de diffuser ces vidéos et que celles-ci n\'enfreignent pas les <a href="./terms_of_use.php" target="_blank">Conditions d\'utilisation</a>.',
 '_bx_videos_info' => 'Infos du fichier',
 '_bx_videos_info_main' => 'Infos principales de la Vidéo',
 '_bx_videos_latest' => 'Dernière vidéo de ce membre',
 '_bx_videos_latest_file' => 'Dernière vidéo appréciée',
 '_bx_videos_main' => 'Principal',
 '_bx_videos_menu_manage' => 'Gérer',
 '_bx_videos_menu_pending' => 'En Attente',
 '_bx_videos_menu_profile' => 'Vidéos',
 '_bx_videos_my' => 'Mes Vidéos',
 '_bx_videos_msg_page_not_found' => 'Page non trouvée',
 '_bx_videos_not_found' => 'Fichier non trouvé',
 '_bx_videos_organize_objects' => 'Organiser',
 '_bx_videos_pending' => 'En Attente',
 '_bx_videos_processing' => 'Traitement',
 '_bx_videos_plural' => 'Vidéos',
 '_bx_videos_preview' => 'Aperçu',
 '_bx_videos_previous_rated' => 'Notées précédemment',
 '_bx_videos_profile_album_name' => 'Vidéos de {0}',
 '_bx_videos_public' => 'Les dernières vidéos',
 '_bx_videos_rate' => 'Noter',
 '_bx_videos_record' => 'Enregistrer',
 '_bx_videos_rate_header' => 'Noter',
 '_bx_videos_regular' => 'Régulier',
 '_bx_videos_related' => 'Vidéos similaires',
 '_bx_videos_save_success' => 'infos du fichier enregistrées',
 '_bx_videos_sbs_main' => 'Vidéo mise à jour',
 '_bx_videos_sbs_comments' => 'Nouveau commentaires de vidéo',
 '_bx_videos_sbs_rates' => 'Nouveau vote de la vidéo',
 '_bx_videos_single' => 'Vidéo',
 '_bx_videos_size' => 'Taille',
 '_bx_videos_size_unit' => 'Kb',
 '_bx_videos_special' => 'Vidéo en vedette',
 '_bx_videos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> a ajouté une nouvelle vidéo <a href="{entry_url}">{entry_caption}</a>',
 '_bx_videos_spy_comment_posted' => '<a href="{entry_url}">la vidéo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a> a été commentée par <a href="{profile_link}">{profile_nick}</a>',
 '_bx_videos_spy_rated' => '<a href="{entry_url}">la vidéo</a> de <a href="{recipient_p_link}">{recipient_p_nick}</a> a été notée par <a href="{profile_link}">{profile_nick}</a>',
  '_bx_videos_submit' => 'Envoyer',
  '_bx_videos_top' => 'Top Vidéos',
  '_bx_videos_top_menu_all' => 'Toutes les Vidéos',
  '_bx_videos_top_menu_album' => 'Album Vidéo',
  '_bx_videos_top_menu_albums' => 'Les albums vidéo',
  '_bx_videos_top_menu_calendar' => 'Calendrier',
  '_bx_videos_top_menu_categories' => 'Catégories',
  '_bx_videos_top_menu_category' => 'Catégorie',
  '_bx_videos_top_menu_favorited' => 'Mes vidéos favorites',
  '_bx_videos_top_menu_featured' => 'Vidéos en vedette',
  '_bx_videos_top_menu_home' => 'Accueil Vidéos',
  '_bx_videos_top_menu_item' => 'Vidéos',
  '_bx_videos_top_menu_popular' => 'Vidéos populaires',
  '_bx_videos_top_menu_profile' => 'Vidéos des Profils',
  '_bx_videos_top_menu_rate' => 'Voter les vidéos',
  '_bx_videos_top_menu_search' => 'Recherche',
  '_bx_videos_top_menu_tags' => 'Etiquettes',
  '_bx_videos_top_menu_top' => 'Top Vidéos',
  '_bx_videos_undefined' => 'Non défini',
  '_bx_videos_emb_err' => 'L\'enrobage de la vidéo a échoué',
  '_bx_videos_upl_err' => 'échec chargement de la vidéo (failed to accept information)',
  '_bx_videos_upl_file_err' => 'échec téléchargement de la vidéo (Video error)',
  '_bx_videos_upl_succ' => 'La vidéo est bien ajoutée',
  '_bx_videos_upload' => 'Vidéos',
  '_bx_videos_val_descr_err' => 'La description ne peut être vide',
  '_bx_videos_val_title_err' => 'Le titre ne peut être vide',
  '_bx_videos_Video_block' => 'Vidéos du profil',
  '_bx_videos_view' => 'Voir la Vidéo',
  '_bx_videos_view_alt_fav' => 'Favoris',
  '_bx_videos_view_alt_view' => 'Vue',
  '_bx_videos_wall_added_new' => 'nouvelle ajoutée',
  '_bx_videos_wall_video' => 'video',
  '_bx_videos_wall_video_private' => 'vidéo privée',
  '_sbs_txt_title_bx_videos' => 'Souscription à la vidéo',
  '_mma_videos_add' => 'ajouter une vidéo',
  '_mma_videos_view' => 'voir les vidéos',
  '_mma_videos_delete' => 'supprimer une vidéo',
  '_mma_videos_download' => 'téléchargement de vidéos',
  '_mma_videos_approve' => 'approuver les vidéos',
  '_mma_videos_edit' => 'éditer une vidéo',
  '_bx_videos_profile_videos' => 'Vidéos du profil',
);

?>
