<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'BooneEx Events';

$aLangContent = array(
    '_sbs_txt_title_bx_events' => 'Événement ',
    '_bx_events' => 'Événement ',
    '_bx_events_single' => 'Événement ',
    '_bx_events_plural' => 'Événement ',
    '_bx_events_action_events_home' => 'Accueil des Événement',
    '_bx_events_action_remove_from_featured' => 'Supprimer de Vedette',
    '_bx_events_action_add_to_featured' => 'Ajouter en Vedette',
    '_bx_events_action_create_event' => 'Créer un événement',
    '_bx_events_action_my_events' => 'Mes événements',
	'_bx_events_action_title_delete' => 'Supprimer',
	'_bx_events_action_title_edit' => 'Editer',
	'_bx_events_action_title_invite' => 'Inviter',
	'_bx_events_action_title_leave' => 'Quitter',
	'_bx_events_action_title_join' => 'Joindre',
    '_bx_events_action_title_share' => 'Partager',
    '_bx_events_action_title_broadcast' => 'Diffuser',    
    '_bx_events_action_manage_fans' => 'Gérer les participants',
    '_bx_events_action_upload_photos' => 'Ajouter des photos',
    '_bx_events_action_upload_videos' => 'Ajouter des vidéos',
    '_bx_events_action_upload_sounds' => 'Ajouter des musiques',
    '_bx_events_action_upload_files' => 'Ajouter des fichiers',
    '_bx_events_add_new_event_admin' => 'Créer un événement',
    '_bx_events_user_unknown' => 'Inconnu',
    '_bx_events_admin' => 'admin',    
	'_bx_events_admin_activate' => 'Activer',	
    '_bx_events_admin_delete' => 'Supprimer',
    '_bx_events_admin_events' => 'Admin Evénements',
    '_bx_events_admin_home' => 'Accueil',
    '_bx_events_administration' => 'Administration événements',
    '_bx_events_administration_create_event' => 'Créer un événement', 
    '_bx_events_administration_settings' => 'Paramètres', 
    '_bx_events_administration_admin_events' => 'Admin Evénements',
	'_bx_events_all_countries' => 'Tous les pays',
	'_bx_events_allow_comments_all' => 'Tous',
	'_bx_events_allow_comments_friends' => 'Uniquement les amis',
	'_bx_events_allow_comments_none' => 'Personne',
	'_bx_events_allow_comments_participants' => 'Uniquement les participants',
	'_bx_events_allow_rate_all' => 'Tous',
	'_bx_events_allow_rate_friends' => 'Uniquement les amis',
	'_bx_events_allow_rate_none' => 'Personne',
	'_bx_events_allow_rate_participants' => 'Uniquement les participants',
    '_bx_events_calendar' => 'Calendrier ',
    '_bx_events_spy_post' => '<a href="{profile_link}">{profile_nick}</a> a ajouté un nouvel événement <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> a changé un événement <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_join' => '<a href="{profile_link}">{profile_nick}</a> a joint un événement <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> a évalué un événement <a href="{entry_url}">{entry_title}</a>',
    '_bx_events_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> a commenté un événement <a href="{entry_url}">{entry_title}</a>',

    '_bx_events_sbs_change' => 'l\'information a été mise à jour',
    '_bx_events_sbs_comment' => 'un nouveau commentaire est arrivé',
    '_bx_events_sbs_rate' => 'l\'évaluation a été mise à jour',
    '_bx_events_sbs_join' => 'nouveau participant',

	'_bx_events_caption_add' => 'Créer un événement', 
	'_bx_events_caption_allow_comments' => 'Autoriser de voir et de publier des commentaires',
	'_bx_events_caption_allow_rate' => 'Autoriser l\évaluation',
	'_bx_events_caption_allow_view_participants' => 'Autoriser de voir les participants',
	'_bx_events_caption_author_id' => 'Auteur ID',
    '_bx_events_caption_browse_by_author' => 'Parcourir les événements par auteur: ',
    '_bx_events_caption_browse_by_author_joined_events' => 'Parcourir les événements joints de l\'auteur: ',
    '_bx_events_caption_browse_by_country' => 'Parcourir les événements par pays: ',
    '_bx_events_caption_browse_by_category' => 'Parcourir les événements par catégorie: ',
    '_bx_events_caption_browse_by_day' => 'Parcourir les événements par jour: ',
    '_bx_events_caption_browse_by_tag' => 'Parcourir les événements par tag: ',
    '_bx_events_caption_browse_featured' => 'Evénements en vedette',
    '_bx_events_caption_browse_popular' => 'Evénements populaires',
    '_bx_events_caption_browse_recently_added' => 'Evénements ajoutés récemment',
    '_bx_events_caption_browse_top_rated' => 'Evénements les mieux notés',
    '_bx_events_caption_browse_upcoming' => 'Evenements à venir',
    '_bx_events_caption_browse_past' => 'Evénements passés',
	'_bx_events_caption_city' => 'Ville',
	'_bx_events_caption_country' => 'Pays',
	'_bx_events_caption_desc' => 'Description',
	'_bx_events_caption_edit' => 'Editer un événement',
	'_bx_events_caption_event_end' => 'Date de fin',
	'_bx_events_caption_event_start' => 'Date de départ',
	'_bx_events_caption_invite' => 'Envoyer une invitation à ',
	'_bx_events_caption_join_filter' => 'Allow to join',
	'_bx_events_caption_keyword' => 'Mot de passe',
	'_bx_events_caption_membership_filter' => 'Allow joining by membership',
	'_bx_events_caption_photo' => 'Photo',
	'_bx_events_caption_place' => 'Nom du lieu',
    '_bx_events_caption_search' => 'Recherche',
    '_bx_events_caption_search_results' => 'Recherche des résultats:',
	'_bx_events_caption_title' => 'Titre',	
    '_bx_events_caption_share_event' => 'Partager',
    '_bx_events_caption_videos' => 'Vidéos',
    '_bx_events_caption_photos' => 'Photos',
    '_bx_events_caption_sounds' => 'Musiques',
    '_bx_events_caption_files' => 'Fichiers',
    '_bx_events_caption_comments' => 'Commentaires',
    '_bx_events_caption_participants' => 'Participants',
    '_bx_events_caption_broadcast' => 'Diffuser un message aux participants de l\'événement',
    '_bx_events_caption_manage_fans' => 'Gérer les participants',
    '_bx_events_caption_upload_photos' => 'Ajouter des photos',
    '_bx_events_caption_upload_videos' => 'Ajouter de vidéos',
    '_bx_events_caption_upload_sounds' => 'Ajouter des musiques',
    '_bx_events_caption_upload_files' => 'Ajouter des fichiers',

	'_bx_events_err_allow_comments' => 'valeur incorrecte',
	'_bx_events_err_allow_rate' => 'valeur incorrecte',
	'_bx_events_err_allow_view_participants' => 'valeur incorrecte',
	'_bx_events_err_city' => 'please fill in city name',
	'_bx_events_err_country' => 'please specify country',
	'_bx_events_err_desc' => 'please specify description from 20 characters',
	'_bx_events_err_event_end' => 'date format is incorrect',
	'_bx_events_err_event_start' => 'date format is incorrect',
	'_bx_events_err_join_filter' => 'incorrect value',
	'_bx_events_err_keyword' => 'please specify keyword from 3 to 100 characters',
	'_bx_events_err_membership_filter' => 'incorrect value',
	'_bx_events_err_photo' => 'please select a photo',
	'_bx_events_err_place' => 'this is a required field',
	'_bx_events_err_tags' => 'please enter at least one word which describes this event',
	'_bx_events_err_title' => 'please specify title from 3 to 100 characters',
    '_bx_events_error_occured' => 'Error Occurred',

    '_bx_events_form_header_info' => 'Event\'s Info',
    '_bx_events_form_header_privacy' => 'Event\'s Privacy Settings',

    '_bx_events_form_caption_file_title' => 'Title:',
    '_bx_events_form_header_images' => 'Event\'s Photos',
    '_bx_events_form_caption_thumb_choice' => 'Choose thumbnail',
    '_bx_events_form_info_thumb_choice' => 'You can choose any uploaded image as event thumnail',
    '_bx_events_form_caption_images_choice' => 'Choose',
    '_bx_events_form_info_images_choice' => 'Unchecked images will be deleted',
    '_bx_events_form_caption_images_upload' => 'Upload',
    '_bx_events_form_info_images_upload' => 'Image will be placed in the "Events" category automatically',

    '_bx_events_form_header_videos' => 'Event\'s Videos',
    '_bx_events_form_caption_videos_choice' => 'Choose',
    '_bx_events_form_info_videos_choice' => 'Unchecked videos will be deleted',
    '_bx_events_form_caption_videos_upload' => 'Upload',
    '_bx_events_form_info_videos_upload' => 'Video will be placed in the "Events" category automatically',

    '_bx_events_form_header_sounds' => 'Event\'s Sounds',
    '_bx_events_form_caption_sounds_choice' => 'Choose',
    '_bx_events_form_info_sounds_choice' => 'Unchecked sounds will be deleted',
    '_bx_events_form_caption_sounds_upload' => 'Upload',
    '_bx_events_form_info_sounds_upload' => 'Sound will be placed in the "Events" category automatically',

    '_bx_events_form_header_files' => 'Event\'s Files',
    '_bx_events_form_caption_files_choice' => 'Choose',
    '_bx_events_form_info_files_choice' => 'Unchecked files will be deleted',
    '_bx_events_form_caption_files_upload' => 'Upload',
    '_bx_events_form_info_files_upload' => 'File will be placed in the "Events" category automatically',

    '_bx_events_form_caption_broadcast_title' => 'Broadcast Title',
    '_bx_events_form_err_broadcast_title' => 'Please enter from 3 to 100 characters',
    '_bx_events_form_caption_broadcast_message' => 'Broadcast Message',
    '_bx_events_form_err_broadcast_message' => 'Please enter at least 10 characters',

    '_bx_events_form_caption_join_confirmation' => 'Join confirmation',
    '_bx_events_form_info_join_confirmation' => 'If enabled, event admin(s) will have to confirm each user before he/she becomes a participant.',
    '_bx_events_form_join_confirmation_disabled' => 'Disabled',
    '_bx_events_form_join_confirmation_enabled' => 'Enabled',

    '_bx_events_event_join_success' => 'You have successfully joined this event',
    '_bx_events_event_joined_already' => 'You have already joined this event',
    '_bx_events_event_join_success_pending' => 'You have successfully joined this event, please wait while your request is reviewed by event admin(s)',
    '_bx_events_event_joined_already_pending' => 'Your join request is pending approval.',    
	'_bx_events_event_leave_success' => 'You have successfully left this event',
	'_bx_events_event_was_deleted' => 'Event was deleted',	
	'_bx_events_info_allow_comments' => 'only these members will be able to view and post comments',
	'_bx_events_info_allow_rete' => 'only these members will be able to rate the event',
    '_bx_events_info_allow_view_participants' => 'only these members will be able to view the participants list',
    '_bx_events_info_author' => 'you can see profile\\\'s ID in admin panel member\\\'s list',
	'_bx_events_info_join_filter' => 'only these members will be able to join this event',	
    '_bx_events_info_membership_filter' => 'only these members will be able to join this event',
    '_bx_events_invitation_sent' => '%d invitations have been sent',

	'_bx_events_join_all' => 'All',
	'_bx_events_join_friends_only' => 'Friends Only',
	'_bx_events_main' => 'Events',
    '_bx_events_membership_filter_none' => 'Allow All',	
	'_bx_events_msg_access_denied' => 'Access Denied',
	'_bx_events_msg_page_not_found' => 'Page Not Found',
    '_bx_events_msg_pending_approval' => 'This event is pending administrator approval. Please, wait.',
    '_bx_events_msg_added_to_featured' => 'Event was added to featured',
    '_bx_events_msg_removed_from_featured' => 'Event was removed from featured',
    '_bx_events_msg_you_have_pending_approval_events' => 'You have <a href="%s">%d pending approval events</a>',
    '_bx_events_msg_you_have_no_events' => 'You have not added any events. <a href="%s">Click here</a> to add one.',
    '_bx_events_msg_you_have_some_events' => 'You have <a href="%s">%d event(s)</a>. <a href="%s">Click here</a> to add more.',
    '_bx_events_msg_broadcast_no_participants' => 'This event has no participants yet',
    '_bx_events_msg_broadcast_message_sent' => 'Broadcast message has been successfully sent',
	'_bx_events_no_users_msg' => 'There are no users in your contacts',
	'_bx_events_pending_approval' => 'Pending Approval',
	'_bx_events_photo_is_pending_approval' => 'Photo is pending approval. Please be patient.',	
	'_bx_events_settings_admin' => 'Settings',

    '_bx_events_privacy_view_event' => 'View Event',
    '_bx_events_privacy_join' => 'Allow joining',
    '_bx_events_privacy_comment' => 'Allow to view and post comments',
    '_bx_events_privacy_rate' => 'Allow rating',
    '_bx_events_privacy_view_participants' => 'Allow viewing participants',
    '_bx_events_privacy_post_in_forum' => 'Allow posting in forum',
    '_bx_events_privacy_participants_only' => 'Participants only',    
    '_bx_events_privacy_participants' => 'Participants',    
    '_bx_events_privacy_admins_only' => 'Admins Only',
    '_bx_events_privacy_upload_photos' => 'Upload Photos',
    '_bx_events_privacy_upload_videos' => 'Upload Videos',
    '_bx_events_privacy_upload_sounds' => 'Upload Sounds',
    '_bx_events_privacy_upload_files' => 'Upload Files',    

    '_bx_events_tags' => 'Events Tags',
    '_bx_events_categories' => 'Events Categories',
	'_bx_events_view_participants_all' => 'All',
	'_bx_events_view_participants_friends' => 'Friends Only',
	'_bx_events_view_participants_none' => 'Nobody',    

    '_bx_events_block_actions' => 'Actions',
    '_bx_events_block_info' => 'Information',
    '_bx_events_block_desc' => 'Description',
    '_bx_events_block_participants' => 'Participants',
    '_bx_events_block_participants_unconfirmed' => 'Unconfirmed Participants',
    '_bx_events_block_photos' => 'Photos',
    '_bx_events_block_videos' => 'Vidéos',
    '_bx_events_block_sounds' => 'Musiques',
    '_bx_events_block_files' => 'Fichiers',
    '_bx_events_block_rate' => 'Evaluer',
    '_bx_events_block_comments' => 'Commentaires',
    '_bx_events_block_calendar' => 'Calendrier des événements',
    '_bx_events_block_upcoming_photo' => 'Upcoming Public Event',
    '_bx_events_block_upcoming_list' => 'Upcoming Public Events',
    '_bx_events_block_past_list' => 'Past Public Events',
    '_bx_events_block_recently_added_list' => 'Recently Added Public Events',
    '_bx_events_block_my_events' => 'My Events',
	'_bx_events_block_joined_events' => 'Joined Events',
    '_bx_events_block_administration' => 'Administration',
    '_bx_events_block_user_events' => 'My Events',
    '_bx_events_block_home' => 'Public Events',

    '_bx_events_block_submenu_main' => 'Principal',
    '_bx_events_block_submenu_add' => 'Ajouter',
    '_bx_events_block_submenu_manage' => 'Gérer',
    '_bx_events_block_submenu_pending' => 'En attente d\'approbation',

    '_bx_events_menu_root' => 'Evénements',
    '_bx_events_menu_main' => 'Accueil Evénements',
    '_bx_events_menu_upcoming_events' => 'A venir',
    '_bx_events_menu_past_events' => 'Past',
    '_bx_events_menu_recently_added' => 'Récemment ajouté',
    '_bx_events_menu_featured' => 'En vedette',
    '_bx_events_menu_my_events' => 'Mes Evénements',
    '_bx_events_menu_my_events_profile' => 'Evénements',
    '_bx_events_menu_my_pending_events' => 'En attente d\'approbation',
    '_bx_events_menu_calendar' => 'Calendrier',
    '_bx_events_menu_popular' => 'Populaire',
    '_bx_events_menu_search' => 'Recherche',
    '_bx_events_menu_tags' => 'Tags',
    '_bx_events_menu_categories' => 'Catégories',
    '_bx_events_menu_top_rated' => 'Les mieux notés',
    '_bx_events_menu_add' => 'Créer un événement',
    '_bx_events_menu_view' => 'Principal',
    '_bx_events_menu_view_forum' => 'Forum',
    '_bx_events_menu_view_comments' => 'Comments',
    '_bx_events_menu_view_participants' => 'Participants',
    '_bx_events_menu_view_photos' => 'Photos',
    '_bx_events_menu_view_videos' => 'Videos',
    '_bx_events_menu_view_sounds' => 'Sounds',
    '_bx_events_menu_view_files' => 'Files',

    '_bx_events_tab_recent' => 'Récemment ajoutés',
    '_bx_events_tab_upcoming' => 'A venir',
    '_bx_events_tab_featured' => 'En vedette',
    '_bx_events_tab_top' => 'Top',
    '_bx_events_tab_popular' => 'Populaire',

    '_bx_event_wall_added_new' => 'a ajouté un nouveau',
    '_bx_event_wall_object' => 'événement',

    '_bx_events_announce' => 'annonce',

    '_mma_events_view' => 'voir les événements', 
    '_mma_events_browse' => 'parcourir les événements', 
    '_mma_events_search' => 'rechercher des événements', 
    '_mma_events_add' => 'ajouter des événements', 
    '_mma_events_comments_delete_and_edit' => 'supprimer et éditer les commentaires des événements', 
    '_mma_events_edit_any_event' => 'events edit any event', 
    '_mma_events_delete_any_event' => 'events delete any event', 
    '_mma_events_mark_as_featured' => 'événements marqués comme vedette', 
    '_mma_events_approve' => 'approuver les événements', 
    '_mma_events_broadcast_message' => 'events broadcast message',
);

?>
