<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/
/*COOL-ON-WEB.COM : TRADUCTION FRANÇAISE : TOUS DROIS RÉSERVÉS - INTERDICTION FORMELLE DE DISTRIBUER CETTE TRADUCTION !! */
$sLangCategory = 'Boonex Files';

$aLangContent = array(
	 '_bx_files_organize_objects' => 'Organiser',
  '_bx_files_pending' => 'En attente',
  '_bx_files_file_block' => 'Fichiers de Profils',
  '_bx_files_plural' => 'fichiers',
  '_bx_files_preview' => 'Aperçu',
  '_bx_files_profile_album_name' => 'Fichiers de {0}',
  '_bx_files_previous_rated' => 'Déjà évalué',
  '_bx_files_public' => 'Fichiers publics',
  '_bx_files_rate' => 'Évaluation',
  '_bx_files_rate_header' => 'Évaluation',
  '_bx_files_record' => 'Enregistrement',
  '_bx_files_regular' => 'Ordinaire',
  '_bx_files_related' => 'Fichiers en relation',
  '_bx_files_save_success' => 'Fichier info a été sauvé',
  '_bx_files_sbs_main' => 'Fichier de mise à jour',
  '_bx_files_sbs_comments' => 'Nouveau Fichier de Commentaires',
  '_bx_files_sbs_rates' => 'Nouveau Fichier de Votes',
  '_bx_files_single' => 'fichier',
  '_bx_files_size' => 'Taille',
  '_bx_files_size_unit' => 'Ko',
  '_bx_files_special' => 'Fichiers en vedette',
  '_bx_files_spy_added' => '<a href="{profile_link}">{profile_nick}</a> a ajouté un nouveau fichier <a href="{entry_url}">{entry_caption}</a>',
  '_bx_files_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">file</a> a été commenté par <a href="{profile_link}">{profile_nick}</a>',
  '_bx_files_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">file</a> a été évalué par <a href="{profile_link}">{profile_nick}</a>',
  
  '_bx_files_submit' => 'Envoyer',
  '_bx_files_top' => 'Les meilleurs fichiers',
  '_bx_files_top_menu_albums' => 'Fichier des dossiers',
  '_bx_files_top_menu_album' => 'Fichier du dossier',
  '_bx_files_top_menu_all' => 'Tous les fichiers',
  '_bx_files_top_menu_calendar' => 'Calendrier',
  '_bx_files_top_menu_categories' => 'Catégories',
  '_bx_files_top_menu_category' => 'Catégorie',
  '_bx_files_top_menu_favorited' => 'Mes fichiers favoris',
  '_bx_files_top_menu_featured' => 'Fichiers mis en vedette',
  '_bx_files_top_menu_home' => 'Accueil Fichiers',
  '_bx_files_top_menu_item' => 'Fichiers',
  '_bx_files_top_menu_popular' => 'Fichiers populaires',
  '_bx_files_top_menu_profile' => 'Fichiers des Profils',
  '_bx_files_top_menu_search' => 'Rechercher',
  '_bx_files_top_menu_tags' => 'Tags',
  '_bx_files_top_menu_top' => 'Les meilleurs fichiers',
  '_bx_files_undefined' => 'Indéfini',
  '_bx_files_upl_err' => 'l\'envoi du fichier a échoué (impossible d\'accepter l\'information)',
  '_bx_files_upl_file_err' => 'l\'envoi du fichier a échoué (erreur de fichier)',
  '_bx_files_upl_succ' => 'Le fichier a été téléchargé avec succès',
  '_bx_files_upload' => 'Fichiers',
  '_bx_files_val_descr_err' => 'La description ne peut pas être vide',
  '_bx_files_val_title_err' => 'Le titre ne peut pas être vide',
  '_bx_files_view' => 'Voir le fichier',
  '_bx_files_view_alt_fav' => 'Favoris',
  '_bx_files_view_alt_view' => 'Vus',
  '_bx_files_wall_added_new' => 'a ajouté un nouveau',
  '_bx_files_wall_file' => 'fichier',
  '_bx_files_wall_file_private' => 'fichier privé',
  '_sbs_txt_title_bx_files' => 'Fichier des abonnements',
   '_bx_files' => 'Fichiers',
  '_bx_files_access_denied' => 'Accés refusé',
  '_bx_files_action_fave' => 'Favori',
  '_bx_files_action_report' => 'Raporter',
  '_bx_files_action_share' => 'Partager',
  '_bx_files_action_download' => 'Télécharger',
  '_bx_files_actions' => 'Actions',
  '_bx_files_add' => 'Ajouter fichier',
  '_bx_files_add_regular' => 'Ordinaire',
  '_bx_files_add_info' => '<a href="{0}">Cliquez ici</a> pour en ajouter un de plus.',
  '_bx_files_add_objects' => 'Ajouter fichiers',
  '_bx_files_admin' => 'Administration',
  '_bx_files_admin_activate' => 'Activer',
  '_bx_files_admin_deactivate' => 'Désactiver',
  '_bx_files_admin_delete' => 'Supprimer',
  '_bx_files_admin_feature' => 'Mettre en vedette',
  '_bx_files_admin_main' => 'Principal',
  '_bx_files_admin_settings' => 'Paramètres',
  '_bx_files_admin_unfeature' => 'Ne pas mettre en vedette',
  '_bx_files_albums_add' => 'Ajouter un dossier',
  '_bx_files_albums_admin' => 'Dossiers administration',
  '_bx_files_albums_disapproved' => 'Mes dossiers refusés',
  '_bx_files_albums_my' => 'Mes fichiers',
  '_bx_files_albums_count_info' => 'Vous avez {0} <a href="{1}">fichier(s)</a>.',
  '_bx_files_albums_add_info' => '<a href="{0}">Cliquez ici</a> pour créer un nouveau dossier.',
  '_bx_files_albums_latest' => 'Dossiers',
  '_bx_files_album' => 'Dossier',
  '_bx_files_album_add' => 'Ajouter',
  '_bx_files_album_add_objects' => 'Ajouter des fichiers',
  '_bx_files_album_delete' => 'Supprimer',
  '_bx_files_album_delete_confirm' => 'Confirmer',
  '_bx_files_album_delete_error' => '{0} fichier(s) sont restés',
  '_bx_files_album_delete_success' => 'Dossier supprimé avec succès',
  '_bx_files_album_delete_warning' => 'Êtes-vous sûr de voulir supprimer l\'intégralité du fichier et de tout son contenu?',
  '_bx_files_album_disapproved' => 'Refusé',
  '_bx_files_album_edit' => 'Edition du dossier',
  '_bx_files_album_info' => 'Dossier d\'infos',
  '_bx_files_album_main' => 'Principal',
  '_bx_files_album_main_objects' => 'Principal',
  '_bx_files_album_manage' => 'Gérer',
  '_bx_files_album_manage_objects' => 'Gérer fichiers',
  '_bx_files_album_manage_objects_disapproved' => 'Refusé',
  '_bx_files_album_manage_objects_pending' => 'En attente',
  '_bx_files_album_objects' => 'Fichiers de ce dossier',
  '_bx_files_album_organize' => 'Organiser',
  '_bx_files_album_organize_reverse' => 'Inverser',
  '_bx_files_album_save_success' => 'L\'info du dossier a été sauvé avec succès',
  '_bx_files_album_view' => 'Autoriser l\'affichage du dossier pour',
  '_bx_files_albums' => 'Dossiers du fichier',
  '_bx_files_alert_commented' => '{0} commenté votre fichier',
  '_bx_files_alert_rated' => 'Le fichier a été commenté',
  '_bx_files_all' => 'Tous les fichiers',
  '_bx_files_any' => 'N\'importe lequel',
  '_bx_files_approved' => 'Approuvé',
  '_bx_files_bcaption_all' => 'Tous les tags',
  '_bx_files_browse' => 'Parcourir',
  '_bx_files_browse_by_album' => 'Parcourir les fichiers du dossier "{0}"',
  '_bx_files_browse_by_tag' => 'Parcourir les fichiers par tag "{0}"',
  '_bx_files_browse_by_category' => 'Parcourir les fichiers par catégorie "{0}"',
  '_bx_files_browse_by_owner' => 'Parcourir les fichiers à partir de {0}',
  '_bx_files_browse_file' => 'Selectionner le fichier',
  '_bx_files_categories_all' => 'Toutes les catégories',
  '_bx_files_choose_uploader' => 'Choisir uploader',
  '_bx_files_close' => 'Fermer',
  '_bx_files_comments' => 'Commentaires',
  '_bx_files_count_info' => 'Vous avez {0} <a href="{1}">fichier(s)</a> dans ce dossier.',
  '_bx_files_couple_file_block' => 'Fichiers de couple',
  '_bx_files_delete' => 'Le fichier a été supprimé',
  '_bx_files_delete_from_album' => 'Supprimer du dossier',
  '_bx_files_delete_error' => 'Erreur lors de la suppression du fichier',
  '_bx_files_disapproved' => 'Refusé',
  '_bx_files_distribute' => 'Conditions pour la distribution des fichiers',
  '_bx_files_download' => 'Télécharger',
  '_bx_files_embed' => 'Insérer',
  '_bx_files_Embed' => 'lien de fichier Flickr',
  '_bx_files_Embed_example' => 'Example: http://www.flickr.com/files/valentina_petrozziello/2939555818/',
  '_bx_files_fav_add' => 'Le fichier a été ajouté à la liste des favoris',
  '_bx_files_fav_failed' => 'Le fichier est déjà dans la liste des favoris',
  '_bx_files_favorited' => 'Mes fichiers favoris',
  '_bx_files_featured' => 'Caractéristiques des fichiers',
  '_bx_files_file_not_found' => 'Fichier non trouvé',
  '_bx_files_file_was_uploaded' => 'Votre fichier a été uploadé (id:{0}) par {1}',
  '_bx_files_forbidden' => 'L\'accès est interdit',
  '_bx_files_home' => 'Accueil des fichiers',
  '_bx_files_i_have_the_right_to_distribute' => 'J\'ai le droit de diffuser ces fichiers',
  '_bx_files_info' => 'Info fichier',
  '_bx_files_info_main' => 'Info du fichier principal',
  '_bx_files_latest' => 'Derniers fichiers de ce membre',
  '_bx_files_latest_file' => 'Fichier du jour',
  '_bx_files_main' => 'Principal',
  '_bx_files_menu_pending' => 'En attente',
  '_bx_files_menu_profile' => 'Fichiers',
  '_bx_files_my' => 'Mes fichiers',
  '_bx_files_msg_page_not_found' => 'Page non trouvée',
  '_bx_files_no_file_for_rate' => 'Pas de fichiers pour l\'évaluation',
   '_bx_files_not_found' => 'Fichier non trouvé',
   	'_mma_files_add' => 'ajouter des fichiers',
	'_mma_files_view' => 'voir des fichiers', 
	'_mma_files_delete' => 'supprimer des fichiers',
	'_mma_files_download' => 'télécharger des fichiers',
	'_mma_files_approve' => 'approuver des fichiers',
	'_mma_files_edit' => 'éditer des fichiers',
);

?>
